name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ["main", "v1", "v2"]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run lint:fix
      # - run: pnpm automd
      - uses: autofix-ci/action@2891949f3779a1cafafae1523058501de3d4e944
        with:
          commit-message: "chore: apply automated updates"
